name: Auto Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/ym-image-processor
          git pull origin main
          docker build -t ym-processor .
          docker stop ym-processor || true
          docker rm ym-processor || true
          docker run -d \
            --name ym-processor \
            --restart always \
            -p 8080:8080 \
            --env-file .env \
            ym-processor
          echo "✅ Deployment completed!"
          docker ps | grep ym-processor